const CardListActionTypes = {
    ADD_CARD: 'ADD_CARD',
    DELETE_CARD: 'DELETE_CARD',
    UPDATE_CARD: 'UPDATE_CARD',
    FETCH_CARD_LIST: 'FETCH_CARD_LIST',
    REFRESH_CARD_LIST: 'REFRESH_CARD_LIST',
    UPDATE_CARD_IS_PUBLIC: 'UPDATE_CARD_IS_PUBLIC'
};

export default CardListActionTypes;